// Auto generated by env plugin. DO NOT EDIT.
type Env = {
  TOSS_APP_NAME: string;
  TOSS_BRAND_DISPLAY_NAME: string;
  TOSS_BRAND_PRIMARY_COLOR: string;
  TOSS_BRAND_ICON_URL: string;
  TOSS_ENABLE_BANNER_ADS: string;
  TOSS_AD_HOME_BANNER_ID: string;
  TOSS_AD_TODAY_BANNER_ID: string;
  TOSS_AD_TAROT_RESULT_BANNER_ID: string;
  TOSS_ENABLE_FULLSCREEN_ADS: string;
};

interface ImportMeta {
  readonly env: Env & {};
}
