/* eslint-disable */
// This file is auto-generated by react-native-bedrock. DO NOT EDIT.
import { Route as _IchingRoute } from '../pages/iching';
import { Route as _IndexRoute } from '../pages/';
import { Route as _SajuRoute } from '../pages/saju';
import { Route as _TarotRoute } from '../pages/tarot';
import { Route as _TarotReadingRoute } from '../pages/tarot/reading';
import { Route as _TarotResultRoute } from '../pages/tarot/result';
import { Route as _TodayRoute } from '../pages/today';

declare module 'react-native-bedrock' {
  interface RegisterScreen {
    '/iching': ReturnType<typeof _IchingRoute.useParams>;
    '/': ReturnType<typeof _IndexRoute.useParams>;
    '/saju': ReturnType<typeof _SajuRoute.useParams>;
    '/tarot': ReturnType<typeof _TarotRoute.useParams>;
    '/tarot/reading': ReturnType<typeof _TarotReadingRoute.useParams>;
    '/tarot/result': ReturnType<typeof _TarotResultRoute.useParams>;
    '/today': ReturnType<typeof _TodayRoute.useParams>;
  }
}
