/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _HistoryRoute } from '../pages/history';
import { Route as _IchingRoute } from '../pages/iching';
import { Route as _IndexRoute } from '../pages/index';
import { Route as _SajuRoute } from '../pages/saju';
import { Route as _TarotRoute } from '../pages/tarot/index';
import { Route as _TarotReadingRoute } from '../pages/tarot/reading';
import { Route as _TarotResultRoute } from '../pages/tarot/result';
import { Route as _TodayRoute } from '../pages/today';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/history': (typeof _HistoryRoute)['_inputType'];
    '/iching': (typeof _IchingRoute)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
    '/saju': (typeof _SajuRoute)['_inputType'];
    '/tarot': (typeof _TarotRoute)['_inputType'];
    '/tarot/reading': (typeof _TarotReadingRoute)['_inputType'];
    '/tarot/result': (typeof _TarotResultRoute)['_inputType'];
    '/today': (typeof _TodayRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/history': (typeof _HistoryRoute)['_outputType'];
    '/iching': (typeof _IchingRoute)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
    '/saju': (typeof _SajuRoute)['_outputType'];
    '/tarot': (typeof _TarotRoute)['_outputType'];
    '/tarot/reading': (typeof _TarotReadingRoute)['_outputType'];
    '/tarot/result': (typeof _TarotResultRoute)['_outputType'];
    '/today': (typeof _TodayRoute)['_outputType'];
  }
}
