/* eslint-disable */
// This file is auto-generated by the Toss RN starter. Run `pnpm router:types` after changing pages.
import { Route as _IndexRoute } from '../pages/index';
import { Route as _SupportRoute } from '../pages/support';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/': (typeof _IndexRoute)['_inputType'];
    '/support': (typeof _SupportRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/': (typeof _IndexRoute)['_outputType'];
    '/support': (typeof _SupportRoute)['_outputType'];
  }
}
