/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _IChingRoute } from '../pages/iching';
import { Route as _IndexRoute } from '../pages/index';
import { Route as _SajuRoute } from '../pages/saju';
import { Route as _TarotIndexRoute } from '../pages/tarot/index';
import { Route as _TarotReadingRoute } from '../pages/tarot/reading';
import { Route as _TarotResultRoute } from '../pages/tarot/result';
import { Route as _TodayRoute } from '../pages/today';
import { Route as _TodayDetailRoute } from '../pages/today/detail';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/iching': (typeof _IChingRoute)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
    '/saju': (typeof _SajuRoute)['_inputType'];
    '/tarot': (typeof _TarotIndexRoute)['_inputType'];
    '/tarot/reading': (typeof _TarotReadingRoute)['_inputType'];
    '/tarot/result': (typeof _TarotResultRoute)['_inputType'];
    '/today': (typeof _TodayRoute)['_inputType'];
    '/today/detail': (typeof _TodayDetailRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/iching': (typeof _IChingRoute)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
    '/saju': (typeof _SajuRoute)['_outputType'];
    '/tarot': (typeof _TarotIndexRoute)['_outputType'];
    '/tarot/reading': (typeof _TarotReadingRoute)['_outputType'];
    '/tarot/result': (typeof _TarotResultRoute)['_outputType'];
    '/today': (typeof _TodayRoute)['_outputType'];
    '/today/detail': (typeof _TodayDetailRoute)['_outputType'];
  }
}
