import type {
  BaseLiquidId,
  MaterialDefinition,
  OrderDefinition,
  PreparedIngredient,
  ScoreBundle,
  TagId,
  UpgradeDefinition,
  WorkbenchId,
} from './types';

function score(
  recovery = 0,
  calm = 0,
  vigor = 0,
  detox = 0,
  purity = 0,
  sideEffect = 0,
): ScoreBundle {
  return {
    recovery,
    calm,
    vigor,
    detox,
    purity,
    sideEffect,
  };
}

export const BASE_LIQUID_LABELS: Record<BaseLiquidId, string> = {
  water: '맹물',
  herbal: '약초 우림',
  refined: '정제 용매',
};

export const TAG_LABELS: Record<TagId, string> = {
  Herb: '약초',
  Flower: '꽃',
  Mineral: '광물',
  Catalyst: '촉매',
  Moonlight: '달빛',
};

export const GRADE_MULTIPLIERS = {
  S: 1.3,
  A: 1.15,
  B: 1,
  C: 0.75,
  F: 0.25,
} as const;

export const RUN_RULE_CHIPS = [
  '7일 1런',
  '주문 2개 중 1개 선택',
  '재료 8개 중 5개 선택',
  '4슬롯 순서 조제',
  '3일/6일 임대료',
];

export const WORKBENCHES: Record<WorkbenchId, { body: string; name: string }> = {
  mortar: {
    name: '절구대',
    body: '즉발 수치를 끌어올리지만 순도나 부작용이 흔들릴 수 있는 손질대',
  },
  drying_rack: {
    name: '건조 선반',
    body: '마지막 슬롯 피니셔를 만드는 후반 마감용 손질대',
  },
  distiller: {
    name: '증류기',
    body: '기반액 전환과 달빛 태그 셋업을 돕는 정제형 손질대',
  },
  purifier: {
    name: '정화대',
    body: '부작용을 줄이고 안정 루트를 열어 주는 안전형 손질대',
  },
};

export const MATERIALS: MaterialDefinition[] = [
  {
    id: 'silverleaf_herb',
    name: '은잎약초',
    rarity: 'common',
    weight: 100,
    family: 'herb',
    defaultTag: 'Herb',
    role: '시작재 / 회복 스타터',
    note: '초반 회복 수치 확보용 기본 스타터',
    base: {
      key: 'base',
      name: '은잎약초',
      passive: score(1, 1),
      effects: [
        {
          when: { type: 'base', anyOf: ['water'] },
          score: { recovery: 1 },
          baseLiquidChange: 'herbal',
          description: '맹물에 바로 우러나 약초 우림을 만들고 회복을 끌어올립니다.',
        },
      ],
    },
    processed: {
      key: 'processed',
      name: '은잎약초 분말',
      workbenchId: 'mortar',
      passive: score(2, 1, 0, 0, -1),
      effects: [
        {
          when: { type: 'slot', anyOf: [1, 2] },
          score: { recovery: 1 },
          description: '앞 슬롯에서 쓰면 회복 스타트가 더 안정됩니다.',
        },
        {
          when: { type: 'base', anyOf: ['water'] },
          baseLiquidChange: 'herbal',
          description: '맹물을 바로 약초 우림으로 바꿉니다.',
        },
      ],
    },
  },
  {
    id: 'white_bark',
    name: '백수피',
    rarity: 'common',
    weight: 95,
    family: 'herb',
    defaultTag: 'Herb',
    role: '회복 브리지 / 안정 루트',
    note: '허브 루트와 정제 루트 둘 다 연결해 주는 중핵 재료',
    base: {
      key: 'base',
      name: '백수피',
      passive: score(2),
      effects: [
        {
          when: { type: 'base', anyOf: ['herbal', 'refined'] },
          score: { recovery: 1, purity: 1 },
          description: '허브 우림이나 정제 용매에서 순도까지 챙겨 줍니다.',
        },
      ],
    },
    processed: {
      key: 'processed',
      name: '정화 백수피',
      workbenchId: 'purifier',
      passive: score(2, 0, 0, 1),
      effects: [
        {
          when: { type: 'base', anyOf: ['herbal', 'refined'] },
          score: { recovery: 1, purity: 1 },
          description: '정화 후에는 해독이 더해져 안정 루트가 넓어집니다.',
        },
      ],
    },
  },
  {
    id: 'sleep_moss',
    name: '잠귀이끼',
    rarity: 'uncommon',
    weight: 70,
    family: 'herb',
    defaultTag: 'Herb',
    role: '진정 브리지 / 달빛 예열',
    note: '진정 루트 핵심. 증류형은 달빛 셋업용',
    base: {
      key: 'base',
      name: '잠귀이끼',
      passive: score(0, 1),
      effects: [
        {
          when: { type: 'base-or-tag', bases: ['herbal'], tags: ['Moonlight'] },
          score: { calm: 2, purity: 1 },
          description: '허브 기반액이나 달빛 태그를 만나면 진정 루프가 크게 붙습니다.',
        },
      ],
    },
    processed: {
      key: 'processed',
      name: '잠귀 증류액',
      workbenchId: 'distiller',
      passive: score(0, 2, 0, 0, 1),
      effects: [
        {
          addTag: 'Moonlight',
          description: '달빛 태그를 깔아 두는 진정 세팅용 증류액입니다.',
        },
      ],
    },
  },
  {
    id: 'moon_blossom',
    name: '달꽃 꽃잎',
    rarity: 'common',
    weight: 95,
    family: 'flower',
    defaultTag: 'Flower',
    role: '진정 코어 / 후반 마감',
    note: '달빛과 결합하면 진정 고점이 크게 오른다',
    base: {
      key: 'base',
      name: '달꽃 꽃잎',
      passive: score(0, 1),
      effects: [
        {
          when: { type: 'base', anyOf: ['herbal'] },
          score: { calm: 1, purity: 1 },
          description: '약초 우림 위에 올리면 순도까지 따라오는 표준 진정 카드가 됩니다.',
        },
        {
          when: { type: 'tag', anyOf: ['Moonlight'] },
          score: { calm: 1 },
          description: '달빛 태그가 있으면 진정이 한 번 더 증폭됩니다.',
        },
      ],
    },
    processed: {
      key: 'processed',
      name: '건조 달꽃',
      workbenchId: 'drying_rack',
      passive: score(0, 1),
      effects: [
        {
          when: { type: 'slot', anyOf: [4, 5] },
          score: { calm: 3 },
          description: '마지막 슬롯 피니셔로 쓰면 진정 수치를 강하게 밀어 줍니다.',
        },
        {
          when: { type: 'tag', anyOf: ['Moonlight'] },
          score: { purity: 1 },
          description: '달빛이 깔려 있으면 마지막 정리 품질도 올라갑니다.',
        },
      ],
    },
  },
  {
    id: 'dawn_rose',
    name: '새벽장미',
    rarity: 'uncommon',
    weight: 70,
    family: 'flower',
    defaultTag: 'Flower',
    role: '활력 피니셔 / 리스크형',
    note: '활력 주문용 핵심 마감재. 원형은 약간 위험하다',
    base: {
      key: 'base',
      name: '새벽장미',
      passive: score(0, 1, 1),
      effects: [
        {
          when: { type: 'base', anyOf: ['herbal'] },
          score: { vigor: 1, sideEffect: 1 },
          description: '허브 우림 위에 올리면 활력 고점이 오르지만 부작용도 늘어납니다.',
        },
      ],
    },
    processed: {
      key: 'processed',
      name: '건조 새벽장미',
      workbenchId: 'drying_rack',
      passive: score(0, 0, 2),
      effects: [
        {
          when: { type: 'slot', anyOf: [4, 5] },
          score: { vigor: 2, sideEffect: -1 },
          description: '건조형은 후반 활력 마감재로 쓰기 좋습니다.',
        },
      ],
    },
  },
  {
    id: 'frost_lily',
    name: '서리백합',
    rarity: 'uncommon',
    weight: 70,
    family: 'flower',
    defaultTag: 'Flower',
    role: '해독 후속재 / 정제 루트',
    note: '광물과 함께 쓰면 해독/순도 둘 다 챙길 수 있다',
    base: {
      key: 'base',
      name: '서리백합',
      passive: score(0, 0, 0, 1),
      effects: [
        {
          when: { type: 'base-or-tag', bases: ['refined'], tags: ['Mineral'] },
          score: { detox: 1, purity: 1 },
          description: '정제 기반액이나 광물 태그를 타면 해독/순도 축이 같이 올라갑니다.',
        },
      ],
    },
    processed: {
      key: 'processed',
      name: '건조 서리백합',
      workbenchId: 'drying_rack',
      passive: score(0, 0, 0, 1),
      effects: [
        {
          when: { type: 'slot', anyOf: [4, 5] },
          score: { detox: 2 },
          description: '후반 정리 슬롯에서 해독 피니셔가 됩니다.',
        },
      ],
    },
  },
  {
    id: 'moonlight_essence',
    name: '월광정수',
    rarity: 'common',
    weight: 80,
    family: 'catalyst',
    defaultTag: 'Catalyst',
    role: '태그 셋업 / 진정 보조',
    note: '직접 점수보다 조합 조건을 열어 주는 촉매',
    base: {
      key: 'base',
      name: '월광정수',
      passive: score(0, 1),
      effects: [
        {
          addTag: 'Moonlight',
          description: '달빛 태그를 즉시 추가합니다.',
        },
      ],
    },
    processed: {
      key: 'processed',
      name: '정제 월광정수',
      workbenchId: 'purifier',
      passive: score(0, 1, 0, 0, 1),
      effects: [
        {
          addTag: 'Moonlight',
          description: '정제 후에는 순도까지 붙는 달빛 셋업 카드가 됩니다.',
        },
      ],
    },
  },
  {
    id: 'honey_crystal',
    name: '꿀수정',
    rarity: 'uncommon',
    weight: 65,
    family: 'catalyst',
    defaultTag: 'Catalyst',
    role: '증폭기 / 고점 엔진',
    note: '직전 재료의 좋은 수치를 복제하는 핵심 촉매',
    base: {
      key: 'base',
      name: '꿀수정',
      passive: score(0, 0, 0, 0, 0, 1),
      effects: [
        {
          amplifyPreviousPositive: 1.5,
          description: '직전 재료의 양수치를 1.50배로 복제합니다.',
        },
      ],
    },
    processed: {
      key: 'processed',
      name: '정제 꿀수정',
      workbenchId: 'purifier',
      passive: score(),
      effects: [
        {
          amplifyPreviousPositive: 1.35,
          description: '직전 재료의 양수치를 1.35배로 증폭합니다.',
        },
      ],
    },
  },
  {
    id: 'silk_sap',
    name: '비단수액',
    rarity: 'uncommon',
    weight: 65,
    family: 'catalyst',
    defaultTag: 'Catalyst',
    role: '기반액 전환 / 순도 확보',
    note: '정제 루트의 가장 안정적인 오프너',
    base: {
      key: 'base',
      name: '비단수액',
      passive: score(0, 0, 0, 0, 1, -1),
      effects: [
        {
          when: { type: 'slot', anyOf: [1] },
          baseLiquidChange: 'refined',
          description: '첫 슬롯에서 정제 용매를 안정적으로 엽니다.',
        },
      ],
    },
    processed: {
      key: 'processed',
      name: '증류 비단수액',
      workbenchId: 'distiller',
      passive: score(0, 0, 0, 0, 1),
      effects: [
        {
          when: { type: 'slot', anyOf: [1] },
          score: { sideEffect: -1 },
          baseLiquidChange: 'refined',
          description: '증류형은 첫 슬롯에서 더 깨끗한 정제 용매를 엽니다.',
        },
      ],
    },
  },
  {
    id: 'star_salt',
    name: '별소금',
    rarity: 'common',
    weight: 85,
    family: 'mineral',
    defaultTag: 'Mineral',
    role: '정화 마감 / 순도 피니셔',
    note: '해독과 순도를 동시에 올리는 대표 마감재',
    base: {
      key: 'base',
      name: '별소금',
      passive: score(0, 0, 0, 0, 1),
      effects: [
        {
          when: { type: 'slot', anyOf: [4, 5] },
          score: { detox: 2, purity: 1, sideEffect: -1 },
          description: '마지막 정리 슬롯에 넣으면 정화 피니셔로 동작합니다.',
        },
      ],
    },
    processed: {
      key: 'processed',
      name: '분쇄 별소금',
      workbenchId: 'mortar',
      passive: score(0, 0, 0, 1, 1),
      effects: [
        {
          when: { type: 'slot', anyOf: [4, 5] },
          score: { detox: 2, sideEffect: -1 },
          description: '분쇄형은 마지막 슬롯 정리력이 더 선명합니다.',
        },
      ],
    },
  },
  {
    id: 'silverstone',
    name: '백은석',
    rarity: 'uncommon',
    weight: 70,
    family: 'mineral',
    defaultTag: 'Mineral',
    role: '강정화 / 부작용 제거',
    note: '부작용이 높게 올라간 빌드를 회수하는 보험',
    base: {
      key: 'base',
      name: '백은석',
      passive: score(0, 0, 0, 1, 0, -2),
      effects: [
        {
          when: { type: 'base', anyOf: ['refined'] },
          score: { purity: 1 },
          description: '정제 용매와 만나면 부작용 회수와 품질 정리를 같이 해 줍니다.',
        },
      ],
    },
    processed: {
      key: 'processed',
      name: '분쇄 백은석',
      workbenchId: 'mortar',
      passive: score(0, 0, 0, 1, -1, -3),
      effects: [
        {
          when: { type: 'base', anyOf: ['refined'] },
          score: { purity: 1 },
          description: '분쇄형은 리스크를 더 크게 정리하지만 순도를 조금 깎습니다.',
        },
      ],
    },
  },
  {
    id: 'black_spores',
    name: '흑포자',
    rarity: 'rare',
    weight: 45,
    family: 'risk',
    role: '고위험 활력 재료',
    note: '후반 정화형으로 쓰면 활력 고점이 크게 오른다',
    base: {
      key: 'base',
      name: '흑포자',
      passive: score(1, 0, 2, 0, 0, 2),
      effects: [
        {
          when: { type: 'base', anyOf: ['herbal'] },
          score: { vigor: 1 },
          description: '약초 우림에서 활력 고점이 한 번 더 튑니다.',
        },
      ],
    },
    processed: {
      key: 'processed',
      name: '정화 흑포자',
      workbenchId: 'purifier',
      passive: score(1, 0, 2),
      effects: [
        {
          when: { type: 'slot', anyOf: [3, 4, 5] },
          score: { vigor: 2 },
          description: '후반 슬롯에서 정화형 활력 피니셔로 터집니다.',
        },
      ],
    },
  },
];

export const ORDERS: OrderDefinition[] = [
  {
    id: 'order_standard_recovery',
    name: '표준 회복제',
    customerLabel: '일반 D1',
    appearanceDay: 1,
    baseReward: 12,
    bonusReward: 3,
    requiredTags: [],
    requiredStats: { recovery: 6 },
    minPurity: 2,
    maxSideEffect: 2,
    bonusTag: 'Herb',
    note: '기본 회복 주문. 초반 회복/허브 조합 감각을 익히는 용도',
    exampleCombo: '은잎약초 -> 백수피 -> 꿀수정 -> 별소금',
  },
  {
    id: 'order_office_sleep',
    name: '불면 사무원 숙면약',
    customerLabel: '일반 D1',
    appearanceDay: 1,
    baseReward: 13,
    bonusReward: 3,
    requiredTags: [],
    requiredStats: { calm: 6 },
    minPurity: 3,
    maxSideEffect: 1,
    bonusTag: 'Moonlight',
    note: '달빛 태그와 진정 루트를 익히는 초반 주문',
    exampleCombo: '은잎약초 -> 잠귀이끼 -> 달꽃 꽃잎 -> 별소금',
  },
  {
    id: 'order_stomach_relief',
    name: '위장 안정제',
    customerLabel: '일반 D1',
    appearanceDay: 1,
    baseReward: 12,
    bonusReward: 3,
    requiredTags: [],
    requiredStats: { recovery: 3, detox: 4 },
    minPurity: 2,
    maxSideEffect: 1,
    bonusTag: 'Mineral',
    note: '정제/광물 루트를 익히는 복합 주문',
    exampleCombo: '비단수액 -> 백수피 -> 서리백합 -> 별소금',
  },
  {
    id: 'order_basic_vigor',
    name: '기본 활력 보급약',
    customerLabel: '일반 D1',
    appearanceDay: 1,
    baseReward: 12,
    bonusReward: 3,
    requiredTags: [],
    requiredStats: { recovery: 2, vigor: 6 },
    minPurity: 0,
    maxSideEffect: 2,
    bonusTag: 'Catalyst',
    note: '촉매/활력 조합을 알려 주는 초반 주문',
    exampleCombo: '은잎약초 -> 새벽장미 -> 백은석 -> 정화 흑포자',
  },
  {
    id: 'order_guild_antidote',
    name: '길드 표준 해독제',
    customerLabel: '길드 D2',
    appearanceDay: 2,
    baseReward: 15,
    bonusReward: 4,
    requiredBase: 'refined',
    requiredTags: [],
    requiredStats: { detox: 5 },
    minPurity: 4,
    maxSideEffect: 1,
    bonusTag: 'Mineral',
    note: '정제 기반액을 명확히 요구하는 해독 시험',
    exampleCombo: '비단수액 -> 서리백합 -> 백은석 -> 별소금',
  },
  {
    id: 'order_field_recovery',
    name: '야전 회복 혼합약',
    customerLabel: '길드 D2',
    appearanceDay: 2,
    baseReward: 14,
    bonusReward: 3,
    requiredTags: [],
    requiredStats: { recovery: 4, calm: 4 },
    minPurity: 2,
    maxSideEffect: 1,
    bonusTag: 'Flower',
    note: '회복/진정 혼합 빌드의 중간 점검',
    exampleCombo: '은잎약초 -> 백수피 -> 잠귀이끼 -> 백은석',
  },
  {
    id: 'order_watchtower_rest',
    name: '망루 당직자의 휴식약',
    customerLabel: '길드 D2',
    appearanceDay: 2,
    baseReward: 15,
    bonusReward: 4,
    requiredTags: ['Herb'],
    requiredStats: { recovery: 3, calm: 5 },
    minPurity: 3,
    maxSideEffect: 1,
    bonusTag: 'Moonlight',
    note: '약초 태그 위에 달빛 마감을 얹는 진정 시험',
    exampleCombo: '은잎약초 -> 백수피 -> 잠귀이끼 -> 달꽃 꽃잎',
  },
  {
    id: 'order_quarry_cleanse',
    name: '채석장 폐세정제',
    customerLabel: '길드 D3',
    appearanceDay: 3,
    baseReward: 16,
    bonusReward: 4,
    requiredTags: ['Mineral'],
    requiredStats: { recovery: 2, detox: 5 },
    minPurity: 3,
    maxSideEffect: 1,
    note: '광물 태그와 해독 루트를 함께 보는 주문',
    exampleCombo: '은잎약초 -> 백은석 -> 서리백합 -> 별소금',
  },
  {
    id: 'order_saloon_calm',
    name: '귀빈 살롱 안정향약',
    customerLabel: '귀족 D3',
    appearanceDay: 3,
    baseReward: 18,
    bonusReward: 4,
    requiredTags: ['Flower'],
    requiredStats: { calm: 6 },
    minPurity: 4,
    maxSideEffect: 0,
    bonusTag: 'Moonlight',
    note: '꽃 태그와 고순도 진정 빌드의 압박 주문',
    exampleCombo: '은잎약초 -> 잠귀이끼 -> 달꽃 꽃잎 -> 별소금',
  },
  {
    id: 'order_banquet_awaken',
    name: '연회용 각성약',
    customerLabel: '귀족 D3',
    appearanceDay: 3,
    baseReward: 17,
    bonusReward: 4,
    requiredTags: ['Flower'],
    requiredStats: { vigor: 7 },
    minPurity: 1,
    maxSideEffect: 1,
    bonusTag: 'Catalyst',
    note: '고점 활력 빌드의 대표 주문',
    exampleCombo: '은잎약초 -> 비단수액 -> 흑포자 -> 건조 새벽장미',
  },
  {
    id: 'order_court_purifier',
    name: '궁정 피부정화제',
    customerLabel: '귀족 D4',
    appearanceDay: 4,
    baseReward: 19,
    bonusReward: 5,
    requiredBase: 'refined',
    requiredTags: [],
    requiredStats: { detox: 5 },
    minPurity: 5,
    maxSideEffect: 0,
    bonusTag: 'Mineral',
    note: '정제 해독 루트의 상위 시험',
    exampleCombo: '비단수액 -> 서리백합 -> 백은석 -> 별소금',
  },
  {
    id: 'order_emergency_ointment',
    name: '응급 전장 연고',
    customerLabel: '특수 D4',
    appearanceDay: 4,
    baseReward: 17,
    bonusReward: 4,
    requiredTags: ['Herb'],
    requiredStats: { recovery: 7, calm: 2 },
    minPurity: 0,
    maxSideEffect: 2,
    bonusTag: 'Catalyst',
    note: '분말 시작재와 증폭기를 노리는 응급 주문',
    exampleCombo: '은잎약초 분말 -> 백수피 -> 꿀수정 -> 잠귀이끼',
  },
  {
    id: 'order_midnight_courier',
    name: '한밤 전령 자극제',
    customerLabel: '특수 D4',
    appearanceDay: 4,
    baseReward: 16,
    bonusReward: 3,
    requiredTags: [],
    requiredStats: { recovery: 2, vigor: 7 },
    minPurity: 0,
    maxSideEffect: 2,
    bonusTag: 'Catalyst',
    note: '활력 고점과 촉매 태그를 압박하는 주문',
    exampleCombo: '은잎약초 -> 백은석 -> 흑포자 -> 건조 새벽장미',
  },
  {
    id: 'order_poison_countermix',
    name: '독장수 카운터믹스',
    customerLabel: '특수 D5',
    appearanceDay: 5,
    baseReward: 19,
    bonusReward: 4,
    requiredTags: ['Mineral'],
    requiredStats: { recovery: 3, detox: 4 },
    minPurity: 4,
    maxSideEffect: 1,
    note: '광물/정제 혼합 루트의 안정성 체크',
    exampleCombo: '비단수액 -> 백수피 -> 서리백합 -> 별소금',
  },
  {
    id: 'order_plague_pacifier',
    name: '전역병 숙정제',
    customerLabel: '특수 D5',
    appearanceDay: 5,
    baseReward: 19,
    bonusReward: 4,
    requiredTags: [],
    requiredStats: { recovery: 2, calm: 8 },
    minPurity: 3,
    maxSideEffect: 1,
    bonusTag: 'Moonlight',
    note: '달빛 기반 진정 루트의 고난도 주문',
    exampleCombo: '은잎약초 -> 잠귀이끼 -> 정제 월광정수 -> 달꽃 꽃잎',
  },
  {
    id: 'order_backstreet_stimulant',
    name: '뒷골목 강심약',
    customerLabel: '뒷골목 D5',
    appearanceDay: 5,
    baseReward: 20,
    bonusReward: 4,
    requiredTags: ['Catalyst'],
    requiredStats: { recovery: 3, vigor: 7 },
    minPurity: 0,
    maxSideEffect: 3,
    note: '고위험 활력 루트의 대표 주문',
    exampleCombo: '은잎약초 -> 비단수액 -> 흑포자 -> 건조 새벽장미',
  },
  {
    id: 'order_secret_cleanser',
    name: '은밀 세척제',
    customerLabel: '뒷골목 D6',
    appearanceDay: 6,
    baseReward: 18,
    bonusReward: 4,
    requiredTags: [],
    requiredStats: { vigor: 3, detox: 4 },
    minPurity: 1,
    maxSideEffect: 2,
    bonusTag: 'Mineral',
    note: '활력/해독 양쪽을 보게 만드는 후반 주문',
    exampleCombo: '백은석 -> 서리백합 -> 정화 흑포자 -> 별소금',
  },
  {
    id: 'order_guild_audit',
    name: '길드 감사용 표준물약',
    customerLabel: '길드감사 D7',
    appearanceDay: 7,
    baseReward: 26,
    bonusReward: 6,
    requiredBase: 'refined',
    requiredTags: [],
    requiredStats: { recovery: 3, detox: 4 },
    minPurity: 5,
    maxSideEffect: 0,
    bonusTag: 'Moonlight',
    note: '7일 런 전체를 관통하는 최종 감사 주문',
    exampleCombo: '비단수액 -> 백수피 -> 서리백합 -> 별소금',
  },
];

export const RUN_UPGRADES: UpgradeDefinition[] = [
  {
    id: 'upgrade_deep_shelf',
    label: '깊은 선반',
    group: 'materials',
    availableDay: 1,
    effectCode: 'MATERIAL_OFFER_PLUS',
    value: 1,
    body: '다음 날 재료 제시 수 +1',
    note: '초반 정보량과 선택 폭을 동시에 늘리는 기본 업그레이드',
  },
  {
    id: 'upgrade_herb_contract',
    label: '약초 공급 계약',
    group: 'materials',
    availableDay: 1,
    effectCode: 'TAG_WEIGHT_HERB',
    value: 1.5,
    body: '약초 계열 재료 등장 가중치 x1.5',
    note: '회복/진정 루트 안정화',
  },
  {
    id: 'upgrade_flower_contract',
    label: '꽃 공급 계약',
    group: 'materials',
    availableDay: 1,
    effectCode: 'TAG_WEIGHT_FLOWER',
    value: 1.5,
    body: '꽃 계열 재료 등장 가중치 x1.5',
    note: '진정/활력 마감 루트 안정화',
  },
  {
    id: 'upgrade_mineral_contract',
    label: '광물 공급 계약',
    group: 'materials',
    availableDay: 2,
    effectCode: 'TAG_WEIGHT_MINERAL',
    value: 1.5,
    body: '광물 계열 재료 등장 가중치 x1.5',
    note: '정제/해독 빌드 안정화',
  },
  {
    id: 'upgrade_catalyst_contract',
    label: '촉매 공급 계약',
    group: 'materials',
    availableDay: 2,
    effectCode: 'TAG_WEIGHT_CATALYST',
    value: 1.5,
    body: '촉매 계열 재료 등장 가중치 x1.5',
    note: '달빛/증폭/정제용매 루트 안정화',
  },
  {
    id: 'upgrade_preserve_drawer',
    label: '보존 서랍',
    group: 'materials',
    availableDay: 2,
    effectCode: 'SAVE_ONE_UNUSED',
    value: 1,
    body: '사용하지 않은 재료 1개를 다음 날로 이월',
    note: '특정 주문을 위한 보험 재료 보존',
  },
  {
    id: 'upgrade_residual_heat',
    label: '잔열 제어',
    group: 'cauldron',
    availableDay: 1,
    effectCode: 'FIRST_ING_PURITY_PLUS',
    value: 1,
    body: '첫 번째 재료 순도 +1',
    note: '스타터의 안정성을 높인다',
  },
  {
    id: 'upgrade_silver_rim',
    label: '은테두리 항아리',
    group: 'cauldron',
    availableDay: 1,
    effectCode: 'LAST_ING_SIDEFX_MINUS',
    value: 1,
    body: '마지막 재료 부작용 -1',
    note: '마감재의 안정성 증가',
  },
  {
    id: 'upgrade_herb_memory',
    label: '약초 기억층',
    group: 'cauldron',
    availableDay: 2,
    effectCode: 'FIRST_HERB_RECOVERY_PLUS',
    value: 1,
    body: '첫 약초 재료 회복 +1',
    note: '회복 주문과 허브 루트 강화',
  },
  {
    id: 'upgrade_flower_crown',
    label: '화관 증폭층',
    group: 'cauldron',
    availableDay: 2,
    effectCode: 'FIRST_FLOWER_CALM_PLUS',
    value: 1,
    body: '첫 꽃 재료 진정 +1',
    note: '꽃 후속재를 쓰는 주문 강화',
  },
  {
    id: 'upgrade_refined_coil',
    label: '정제 코일',
    group: 'cauldron',
    availableDay: 3,
    effectCode: 'REFINED_TRIGGER_PURITY_PLUS',
    value: 1,
    body: '기반액이 정제 용매로 바뀔 때 순도 +1',
    note: '정제 루트 고점 강화',
  },
  {
    id: 'upgrade_spare_slot',
    label: '예비 슬롯 봉인해제',
    group: 'cauldron',
    availableDay: 4,
    effectCode: 'ONCE_EXTRA_SLOT',
    value: 1,
    valueLabel: '하루 1회',
    body: '하루 한 번 5번째 투입 슬롯 사용 가능',
    note: '최종 감사 전 한 번의 폭발력 확보',
  },
  {
    id: 'upgrade_precision_hammer',
    label: '정밀 망치',
    group: 'workbench',
    availableDay: 2,
    effectCode: 'WORKBENCH_PERFECT_BONUS',
    value: 1,
    body: '손질형 재료의 가장 큰 양수치 +1',
    note: '손질 미니게임 대신 손질 결과를 더 크게 만들어 줌',
  },
  {
    id: 'upgrade_predictive_plate',
    label: '예측 문양판',
    group: 'workbench',
    availableDay: 1,
    effectCode: 'FULL_PREVIEW',
    value: 1,
    body: '프리뷰에 전체 수치 변화와 반응 로그를 표시',
    note: '가독성 강화형 업그레이드',
  },
  {
    id: 'upgrade_wash_basin',
    label: '정화 세면대',
    group: 'workbench',
    availableDay: 3,
    effectCode: 'PROCESSED_SIDEFX_MINUS',
    value: 1,
    body: '손질형 재료의 부작용 -1',
    note: '위험 재료를 더 안전하게 사용 가능',
  },
  {
    id: 'upgrade_calibration_jig',
    label: '교정 지그',
    group: 'workbench',
    availableDay: 3,
    effectCode: 'PROCESSED_PURITY_PLUS',
    value: 1,
    body: '손질형 재료의 순도 +1',
    note: '손질형 마감재/정제재 가치 상승',
  },
];

export function createIngredient(materialId: string, source: PreparedIngredient['source']): PreparedIngredient {
  const material = getMaterialById(materialId);
  return {
    instanceId: `${materialId}-${Math.random().toString(36).slice(2, 8)}`,
    materialId,
    formKey: 'base',
    family: material.family,
    defaultTag: material.defaultTag,
    name: material.name,
    source,
  };
}

export function getMaterialById(materialId: string): MaterialDefinition {
  const material = MATERIALS.find((candidate) => candidate.id === materialId);
  if (!material) {
    throw new Error(`Unknown material: ${materialId}`);
  }

  return material;
}

export function getMaterialForm(ingredient: PreparedIngredient) {
  const material = getMaterialById(ingredient.materialId);
  return ingredient.formKey === 'processed' ? material.processed ?? material.base : material.base;
}

export function getOrderById(orderId: string): OrderDefinition {
  const order = ORDERS.find((candidate) => candidate.id === orderId);
  if (!order) {
    throw new Error(`Unknown order: ${orderId}`);
  }

  return order;
}

export function getUpgradeById(upgradeId: string): UpgradeDefinition {
  const upgrade = RUN_UPGRADES.find((candidate) => candidate.id === upgradeId);
  if (!upgrade) {
    throw new Error(`Unknown upgrade: ${upgradeId}`);
  }

  return upgrade;
}
