#!/usr/bin/env bash
set -euo pipefail

STACK=${1:-webapp}
NAME=${2:-my-app}
TARGET=${3:-$(pwd)/$NAME}

if [[ "$STACK" == "mobile" ]]; then
  if ! command -v flutter >/dev/null 2>&1; then
    echo "flutter not found. install Flutter to use mobile stack"
    exit 1
  fi
  flutter create "$TARGET" --project-name "$(echo "$NAME" | tr '-' '_' | tr -cd 'a-zA-Z0-9_')"
  if [[ -f "$TARGET/README.md" ]]; then
    printf "\n## Starter Notes\n- Generated by vibe-starter mobile stack\n" >> "$TARGET/README.md"
  fi
  echo "initialized: $TARGET (stack=mobile)"
  exit 0
fi

TEMPLATE_DIR="$(cd "$(dirname "$0")/.." && pwd)/templates/$STACK"
if [[ ! -d "$TEMPLATE_DIR" ]]; then
  echo "unknown stack: $STACK (use: webapp|bot|cli|mobile|toss-rn-miniapp)"
  exit 1
fi

mkdir -p "$TARGET"
cp -R "$TEMPLATE_DIR"/. "$TARGET"/

if [[ -f "$TARGET/README.md" ]]; then
  sed -i "s/{{PROJECT_NAME}}/$NAME/g" "$TARGET/README.md"
fi

echo "initialized: $TARGET (stack=$STACK)"
